FROM debian:latest

# RUN echo 'deb http://deb.debian.org/debian experimental main' >> /etc/apt/sources.list

# python-neovim python3-neovim
RUN apt-get update && apt install -y git zsh neovim 

CMD bash
